### ISSUE TITLE
v0.4 Breaks Dialogic 2 addon on export

### ISSUE THREAD

**Issue by bazsupport** [derkork/godot-resource-groups#14]
Hello, currently our project uses both Dialogic 2 and Resource Groups. I noticed on the latest updates that if I am to build a game now I believe that Resource Groups is grabbing all the addons/dialogic folder stuff as well as the .dtl and .dch (there might be more I'm trying to come up with a cumulative Dialogic resource list).

I'm trying to exclude stuff using a resource groups tres but for some reason Dialogic 2 timelines will still not work on builds
Here is the related github post about it, both the owner and me use Resource Groups and thats why they couldnt figure out what was happening. I just had this realization today:
https://github.com/dialogic-godot/dialogic/issues/2468

could you please help with this? Im trying my best to solve as well and will let you know if i find something

**Comment by derkork** [comment]
The one thing that was changed in 0.4 was to add an export plugin which ensures the groups are up-to-date before the export is running. For some odd reason only the mere presence of an export plugin seems to break dialogic (e.g. i removed the whole implementation and just added an empty export plugin). I'm still trying to find out why that is, it's surely a strange problem.

**Comment by derkork** [comment]
I think i found a workaround. In the process I also found a way to considerably speed up scanning :D I'll push a new release.
