### ISSUE TITLE
ResourceGroup Paths Not Updating Automatically in Godot 4.3 After Plugin Enablement

### ISSUE THREAD

**Issue by heartcraftcat** [derkork/godot-resource-groups#15]
I encountered the following issue: 
After adding and enabling the plugin, I created a new ResourceGroup and set the base folder. 

I saved the scene, but the paths did not update automatically, and the size remained displayed as 0 (only after running the project did the paths update automatically, and at that point, the size was displayed correctly). 

The version of Godot I am using is v4.3.stable.official [77dcf97d8]. 

Note: Besides this plugin, I only have the Dialogue plugin installed.The auto-update feature in the project settings is also enabled.

**Comment by heartcraftcat** [comment]
![image](https://github.com/user-attachments/assets/53c54c84-d0a1-48be-aa0c-e9e312635168)

**Comment by derkork** [comment]
This has been changed in 0.4.0. The paths will only update when you run the project not on every save. This is because updating the paths requires scanning the whole project which can introduce slowness in projects with lots of files. So the scan is only done once before the game starts.

**Comment by heartcraftcat** [comment]
got it.Thanks a lot!
