### ISSUE TITLE
Auto Rebuild does not work in C# Projects

### ISSUE THREAD

**Issue by Genae** [derkork/godot-resource-groups#19]
Hey,

~~Looks like I am unable to make a pull request so here is an issue :)~~

~~The C# version of the ResourceGroup needs to extend Ressource otherwise it is not possible to [Export] ResourceGroup Attributes:~~

~~`public partial class ResourceGroup: Resource`~~

<img width="444" alt="image" src="https://github.com/user-attachments/assets/afb10ac6-0990-402a-988d-66c1748b72f8" />

Nevermind you are not supposed to do this. Instead I now 
`[Export] Resource _res;`
and then I can use the 
`ResourceGroup.Of(_res)`
and that works like a charm

**Comment by Genae** [comment]
hmm, also the ResourceGroup collection seems to be broken in C#.
I tried adding the [Tool] Attribute above the ResourceGroup as well as the ResourceGroupBackgroundLoader, but no Luck so far:
<img width="359" alt="image" src="https://github.com/user-attachments/assets/c8097651-4e70-4e08-974e-465223ef2a9e" />
<img width="356" alt="image" src="https://github.com/user-attachments/assets/24256247-b473-4738-bb76-6e93aabec449" />

**Comment by derkork** [comment]
> Nevermind you are not supposed to do this. Instead I now `[Export] Resource _res;` and then I can use the `ResourceGroup.Of(_res)` and that works like a charm

Yes this is not ideal. But C# classes cannot inherit from GDScript classes, so the C# `ResourceGroup` class is actually just a wrapper around the GDScript resource with every drawback that entails. I would love if exporting was possible directly but right now this doesn't seem to be an option, so we have to forego some type safety here and manually wrap the wrapper around a plain `Resource` object.

> However the automatic rebuild does not work, even when the "Auto Rebuild" checkbox in the settings is enabled.

The resource groups are only rebuilt when the game starts (this can be turned off  by disabling the _Auto Rebuild_ flag) or is exported. This is to avoid slowing down the editor by constantly scanning for updated resources. It should have no impact on the normal use of the library though - when you run the game to test it and have _Auto Rebuild_ on you should get up-to-date resource groups in your game. Is this not working for you?

**Comment by Genae** [comment]
Ah, well, just ignore me, it adds them on game start. I was assuming it would add them on "build". Thanks for the help!
